# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Weapow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='starship',
            name='weapows',
            field=models.ManyToManyField(blank=True, null=True, to='wars.Weapow'),
        ),
    ]
